version: '3.7'
services:
  backend:
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/app
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/app
