export const ADD_ADVERT_START = "ADD_ADVERT_START"
export const ADD_ADVERT_SUCCESS = "ADD_ADVERT_SUCCESS"
export const ADD_ADVERT_ERROR = "ADD_ADVERT_ERROR"

export const FETCH_ADVERT_START = "FETCH_ADVERT_START"
export const FETCH_ADVERT_SUCCESS = "FETCH_ADVERT_SUCCESS"
export const FETCH_ADVERT_ERROR = "FETCH_ADVERT_ERROR"

export const FETCH_ADVERTS_SUCCESS = "FETCH_ADVERTS_SUCCESS"
